[package]
name = "binge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.34", features = ["derive"] }
clap_complete = "4.5.47"
flate2 = "1.1.1"
futures-concurrency = "7.6.3"
futures-lite = "2.6.0"
owo-colors = "4.2.0"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["brotli", "json", "zstd"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tar = "0.4.44"
tempfile = "3.19.1"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
xdg = "2.5.2"
xz2 = "0.1.7"
zip = "2.5.0"
zstd = "0.13.3"
