[licenses]
allow = [
    "MIT",
    "Unicode-3.0",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
